# Generated by Django 4.1.2 on 2022-10-24 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('desc', models.CharField(max_length=256, verbose_name='Description')),
                ('created_on', models.DateField(verbose_name='Created On')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(verbose_name='Created On')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=0.634, max_digits=6, verbose_name='Mileage Rate')),
                ('sumbitted_on', models.DateField(blank=True, null=True, verbose_name='Submitted On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_code', models.IntegerField(choices=[(1000, 'Office Time'), (1200, 'Vacation'), (1300, 'PTO / Sick Time'), (1400, 'Sales/Marketing & R&D'), (1500, 'Warrantee'), (1600, 'Travel Time'), (1700, 'Training'), (2200, 'Technician Labor'), (4200, 'PLC Programming'), (4400, 'HMI/SCADA Programming'), (4800, 'Electrical Design/Eng & Project Management')], verbose_name='Work Code')),
                ('reg_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Regular Hours')),
                ('ovt_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Overtime Hours')),
                ('dbl_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Doubletime Hours')),
                ('desc', models.CharField(max_length=1024, verbose_name='Description of Work')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timetrack.project')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='PartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(max_length=256, verbose_name='Part Description / Part Number')),
                ('notes', models.CharField(max_length=256, verbose_name='Additional Notes for Customer')),
                ('reorder', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Re-Order Part Yes/No')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timetrack.project')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage_rate', models.DecimalField(decimal_places=2, default=0.634, max_digits=5, verbose_name='Mileage Rate')),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Per Diem Food')),
                ('air', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Air Fare')),
                ('parking', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Tolls / Parking')),
                ('meals', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Business Meals')),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Other Expenses')),
                ('other_explain', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Explanation of Expenses')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timetrack.project')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.timesheet')),
            ],
        ),
    ]
